export const API_ENDPOINTS = {
  health: '/health',
  auth: {
    login: '/auth/login',
    me: '/auth/me',
    register: '/auth/register',
    registerSimple: '/auth/register/simple',
    refresh: '/auth/refresh',
  },
  usuarios: '/usuarios',
  roles: '/roles',
  permisos: '/permisos',
  misDestinatarios: '/mis-destinatarios',
  misPaquetes: '/mis-paquetes',
  operarioPaquetes: '/operario/paquetes',
  operarioDistribuidores: '/operario/distribuidores',
  operarioAgencias: '/operario/agencias',
  agencias: '/agencias',
  agenciasDistribuidor: '/agencias-distribuidor',
  distribuidores: '/distribuidores',
  manifiestos: '/manifiestos',
  operarioDestinatarios: '/operario/destinatarios',
  operarioSacas: '/operario/sacas',
  operarioDespachos: '/operario/despachos',
  operarioLotesRecepcion: '/operario/lotes-recepcion',
  tracking: '/tracking',
  configTarifaCalculadora: '/config/tarifa-calculadora',
  configMensajeAgenciaEeuu: '/config/mensaje-agencia-eeuu',
  operarioConfigTarifaCalculadora: '/operario/config/tarifa-calculadora',
  operarioMensajeWhatsAppDespacho: '/operario/config/mensaje-whatsapp-despacho',
  operarioMensajeAgenciaEeuu: '/operario/config/mensaje-agencia-eeuu',
  operarioEstadosRastreo: '/operario/estados-rastreo',
  operarioConfigEstadosRastreoPorPunto: '/operario/config/estados-rastreo-por-punto',
  guiasMaster: '/guias-master',
  enviosConsolidados: '/envios-consolidados',
  misGuias: '/mis-guias',
} as const;
